/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main_window;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import library.Library;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author DAW08-TAREK
 */
public class StadisticsWindow extends javax.swing.JFrame {

    /**
     * Creates new form StadisticsWindow
     */
    public StadisticsWindow(MainWindow parent) {
        try {
            initComponents();
            showInformation();
            responsiveDesign();
        } catch (Exception e) {
            dispose();
        }
    }

    /**
     *
     * @throws Exception
     */
    private void showInformation() throws Exception {
        int num[] = Library.countByAge();
        int infantil = num[0];
        int mayoresDe7 = num[1];
        int mayoresDe12 = num[2];
        int adultos = num[3];
        
        DefaultPieDataset datos = new DefaultPieDataset();
        datos.setValue("Infantil", infantil);
        datos.setValue("Mayores de 7 años", mayoresDe7);
        datos.setValue("Mayores de 12 años", mayoresDe12);
        datos.setValue("Adultos", adultos);
        
        JFreeChart grafico = ChartFactory.createPieChart("Estadisticas de edad de los libros", datos, true, true, false);
        ChartPanel panel = new ChartPanel(grafico);

        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(900, 900));

        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(panel, BorderLayout.CENTER);

        pack();
        repaint();
    }

    /**
     *
     */
    private void responsiveDesign() {
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();
        int height = pantalla.height;
        int width = pantalla.width;
        setSize(width / 4, height / 4);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
